changes
`assets/i18n/i18n.py`:
- Added support for plugins
- When i18n function first argument is:
  - Empty:
    - Return itself (text, regardless of language)
  - Provided, but doesnt exist in the current language:
    - Look for it in English file, if not found return itself (text, regardless of language)

`tabs/inference/inference.py`:
- Added stereo mode
- Audio file path is reset if it is invalid
- Added `Inherit` (from input file format) output format
- Convert button is not clickable if:
   - Terms agreement checkbox is not checked
   - Model path is invalid
   - Audio file path is invalid

`tabs/plugin/plugin.py`:
- Plugin installation will fail if it's not a file

`app.py`:
- If there's no internet connection:
   - Discord RPC will not be loaded
   - Access to following tabs will be disabled:
     - `tts`
     - `download`

`tabs/tts/tts.py`:
- Audio cleaning checkbox is now initially set to false

`core.py`:
- Adding plugin will fail if it will be invalid archive file
- Added HuggingFace download function
- Added shorthands for inference CLI arguments
- Added stereo mode support

`tabs/voice_blender/voice_blender.py`:
- Model A and Model B are now dropdowns, working in same fashion as in `inference` tab
- Fusion button is not clickable if:
   - Model name is empty
   - Model files are invalid
   - Model files have same path

`tabs/download/download.py`
- Download model button will be not clickable if:
   - No internet connection has been established
   - No `http:` or `ftp:` will be found inside model link
   - Sample rate is invalid

`tabs/extra/sections/f0_extractor.py`:
- Extract F0 Curve button will not be clickable if:
   - File is invalid

`tabs/extra/sections/processing.py`:
- View button is not clickable if:
   - Path to model is invalid

`tabs/extra/sections/analyzer.py`:
- Get information about the audio button will be not clickable if:
  - Audio path is invalid

`rvc/infer/infer.py`:
- Added support for `Inherit` export format
- Added stereo mode support
- Fixed `SystemError` occuring from lack of output directory existence in batch conversion
- Fixed the following bug with bitcrush resulting in:
```python
    bitcrush = Bitcrush(bit_depth=kwargs.get("bitcrush_bit_depth", 8))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. pedalboard_native.Bitcrush(bit_depth: float = 8)

Invoked with: kwargs: bit_depth=[{'__type__': 'update', 'visible': True}]
```

`requirements.txt`:
- Added `pydub`

`rvc/lib/predictors/F0Extractor.py`:
- Enhanced `wav16k` to be more fullband

`rvc/lib/utils.py`:
- Enhanced resampling to be more fullband

`README.md`
- Beautified code

`assets/Applio_NoUI.ipynb`
- Beautified code
- Added more features

`logs/models/.keep`
- Added this file in order to ease weights segregation